### ISSUE TITLE
Build failing on Netlify when using the token in an environment variable

### ISSUE THREAD

**Issue by prabuw** [cedricdelpoux/gatsby-source-strava#7]
Hi Cedric,

Thanks for the plugin!

I have set up the plugin and generated the token as the docs have stated. I then added it as an environment variable on the `Netlify` platform, which I'm using to build and deploy my site.

It works nicely in development. It also works on the first build/deployment where I believe the query is first made to the Strava API and the data is persisted in the `.strava` folder.

However, on the next build deployment (via Netlify), the build fails The next deployment is after the current token has expired and there isn't a mechanism to utilise the refresh token to get a new valid token.

Have you come across this before? I am guessing with the current setup there isn't any way around it. Do you have any suggestions?

On another note: I am new to the Gatsby platform/plugins, so this could be a n00b question, but it seems that `gatsby-source-xxxx` plugins will only update the data on build/deployment -- Is this generally accurate?

**Comment by cedricdelpoux** [comment]
Hi @prabuw, sorry for the delay.

Did you use `gatsby-plugin-netlify-cache`? It's documented [here](https://github.com/cedricdelpoux/gatsby-source-strava/blob/master/docs/cache.md#netlify)

**Comment by prabuw** [comment]
No worries @cedricdelpoux. :)

I have used it. If the token has expired (since the last build) then does cache matter?

**Comment by cedricdelpoux** [comment]
`gatsby-source-strava` refresh the token itself but the token need to be persisted between builds

**Comment by prabuw** [comment]
Thanks for the reply. 😄 

I guess that means I need to generate a new token in between builds/deploys if the current token has expired. In my case, I have to replace the token in Netlify's environment variables since I don't want to include it in my source. 

Even if it was in a config file in my source and I haven't run the blog locally within the expiry, then I would have to do the same actions.

Does that sound right?

**Comment by cedricdelpoux** [comment]
No need to include the token in your source code. Use he env variable
Maybe the [documentation](https://github.com/cedricdelpoux/gatsby-source-strava/blob/master/docs/token.md#environment-variable) is not clear enough.
 
The env variable will be useful the first time, then `gatsby-source-strava` refresh the token itself, and create the `.strava` folder with token in it. That's why it's important to use the `gatsby-plugin-netlify-cache` plugin with `extraDirsToCache` option to keep `.strava` folder between builds.

Please update the documentation if you can explain better than me
